# Generated by Django 5.0.1 on 2025-12-20 11:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Password Hash')),
                ('oauth_provider', models.CharField(blank=True, choices=[('google', 'Google'), ('kakao', 'Kakao')], max_length=20, null=True, verbose_name='OAuth Provider')),
                ('oauth_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='OAuth ID')),
                ('profile_image', models.URLField(blank=True, max_length=500, null=True, verbose_name='Profile Image URL')),
                ('timezone', models.CharField(default='Asia/Seoul', max_length=50, verbose_name='Timezone')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Premium Member')),
                ('premium_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Premium Expiration Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sound_enabled', models.BooleanField(default=False, verbose_name='Sound Enabled')),
                ('screen_flash_enabled', models.BooleanField(default=True, verbose_name='Screen Flash Enabled')),
                ('vibration_enabled', models.BooleanField(default=True, verbose_name='Vibration Enabled')),
                ('device_flash_enabled', models.BooleanField(default=False, verbose_name='Device Flash Enabled (Premium)')),
                ('flash_pattern', models.JSONField(blank=True, default=dict, help_text='JSON: {duration: 500, count: 3, interval: 200, color: "#10b981"}', verbose_name='Flash Pattern')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'db_table': 'notification_preferences',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='idx_user_email'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['oauth_provider', 'oauth_id'], name='idx_user_oauth'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_premium', 'premium_expires_at'], name='idx_user_premium'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('oauth_provider__isnull', False)), fields=('oauth_provider', 'oauth_id'), name='unique_oauth_provider_id'),
        ),
        migrations.AddIndex(
            model_name='notificationpreferences',
            index=models.Index(fields=['user'], name='idx_notification_user'),
        ),
    ]
