# Generated by Django 5.0.1 on 2025-12-20 11:16

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Plan Date')),
                ('priorities', models.JSONField(blank=True, default=list, help_text='Array of 3 priority tasks for the day', verbose_name='Priorities')),
                ('brain_dump', models.TextField(blank=True, null=True, verbose_name='Brain Dump')),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Completion Rate (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Daily Plan',
                'verbose_name_plural': 'Daily Plans',
                'db_table': 'daily_plans',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TimeBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('am', 'AM'), ('pm', 'PM')], max_length=2, verbose_name='Period (AM/PM)')),
                ('hour', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Hour (1-12)')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Block Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Category')),
                ('planned_duration', models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Planned Duration (minutes)')),
                ('actual_duration', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Actual Duration (minutes)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Time Block',
                'verbose_name_plural': 'Time Blocks',
                'db_table': 'time_blocks',
                'ordering': ['period', 'hour'],
            },
        ),
    ]
