# Generated by Django 5.0.1 on 2025-12-20 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_plans', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='timeblock',
            name='daily_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_blocks', to='plans.dailyplan', verbose_name='Daily Plan'),
        ),
        migrations.AddIndex(
            model_name='dailyplan',
            index=models.Index(fields=['user', 'date'], name='idx_daily_plan_user_date'),
        ),
        migrations.AddIndex(
            model_name='dailyplan',
            index=models.Index(fields=['date'], name='idx_daily_plan_date'),
        ),
        migrations.AddConstraint(
            model_name='dailyplan',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_user_date'),
        ),
        migrations.AddIndex(
            model_name='timeblock',
            index=models.Index(fields=['daily_plan', 'period', 'hour'], name='idx_timeblock_plan_time'),
        ),
        migrations.AddIndex(
            model_name='timeblock',
            index=models.Index(fields=['category'], name='idx_timeblock_category'),
        ),
        migrations.AddIndex(
            model_name='timeblock',
            index=models.Index(fields=['is_completed'], name='idx_timeblock_completed'),
        ),
        migrations.AddConstraint(
            model_name='timeblock',
            constraint=models.UniqueConstraint(fields=('daily_plan', 'period', 'hour'), name='unique_timeblock_period_hour'),
        ),
    ]
