# Generated by Django 5.0.1 on 2025-12-20 11:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimerSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Scheduled Duration (seconds)')),
                ('elapsed_time', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Elapsed Time (seconds)')),
                ('status', models.CharField(choices=[('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='running', max_length=20, verbose_name='Status')),
                ('started_at', models.DateTimeField(verbose_name='Started At')),
                ('paused_at', models.DateTimeField(blank=True, null=True, verbose_name='Paused At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('time_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timer_sessions', to='plans.timeblock', verbose_name='Time Block (Optional)')),
            ],
            options={
                'verbose_name': 'Timer Session',
                'verbose_name_plural': 'Timer Sessions',
                'db_table': 'timer_sessions',
                'ordering': ['-started_at'],
            },
        ),
    ]
