# Generated by Django 5.0.1 on 2025-12-20 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timer_sessions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='timersession',
            index=models.Index(fields=['user', 'started_at'], name='idx_timer_user_date'),
        ),
        migrations.AddIndex(
            model_name='timersession',
            index=models.Index(fields=['time_block'], name='idx_timer_block'),
        ),
        migrations.AddIndex(
            model_name='timersession',
            index=models.Index(fields=['status'], name='idx_timer_status'),
        ),
        migrations.AddIndex(
            model_name='timersession',
            index=models.Index(fields=['completed_at'], name='idx_timer_completed'),
        ),
    ]
